const pptxgen = require('pptxgenjs');
const fs = require('fs');
const path = require('path');
const { imageSizingContain, warnIfSlideHasOverlaps, warnIfSlideElementsOutOfBounds } = require('/home/oai/skills/slides/pptxgenjs_helpers');
const payload = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const out = process.argv[3];
const pptx = new pptxgen(); pptx.layout='LAYOUT_WIDE'; pptx.author='Purple Falcon'; pptx.subject='Dynamic Deep Data Analysis'; pptx.title=payload.title; pptx.company='Purple Falcon'; pptx.lang='en-US';
pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-US'};
const C={purple:'7137F5',navy:'172033',blue:'4279C6',teal:'15A6A6',orange:'F39C3D',red:'D94A57',light:'F5F2FF',gray:'667085',white:'FFFFFF',black:'151515'};
function base(slide,title,sub=''){slide.background={color:'FFFFFF'};slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:.16,fill:{color:C.purple},line:{color:C.purple}});slide.addText(title,{x:.65,y:.42,w:12,h:.45,fontFace:'Aptos Display',fontSize:26,bold:true,color:C.navy,margin:0});if(sub)slide.addText(sub,{x:.65,y:.92,w:12,h:.28,fontSize:10.5,color:C.gray,margin:0});}
function footer(slide,n){slide.addText(`Purple Falcon Dynamic Report  |  ${n}`,{x:.65,y:7.12,w:12,h:.18,fontSize:8,color:'98A2B3',margin:0,align:'right'});}
function bullets(slide,items,x,y,w,h,fs=16){const runs=[];items.slice(0,9).forEach((t,i)=>{runs.push({text:String(t),options:{bullet:{indent:16},breakLine:true}})});slide.addText(runs,{x,y,w,h,fontSize:fs,color:C.black,breakLine:false,margin:.08,paraSpaceAfterPt:8,valign:'top'});}
function addKpi(slide,x,y,w,label,value,color=C.purple){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h:1.05,rectRadius:.08,fill:{color:'FAFAFC'},line:{color:'E6E6EF'}});slide.addText(String(value),{x:x+.15,y:y+.14,w:w-.3,h:.38,fontSize:23,bold:true,color,margin:0,align:'center'});slide.addText(label,{x:x+.1,y:y+.62,w:w-.2,h:.22,fontSize:10,color:C.gray,margin:0,align:'center'});}
let n=1;
{let s=pptx.addSlide();s.background={color:C.navy};s.addShape(pptx.ShapeType.rect,{x:.75,y:.8,w:.14,h:4.8,fill:{color:C.purple},line:{color:C.purple}});s.addText('PURPLE FALCON',{x:1.1,y:1.05,w:5.5,h:.4,fontSize:16,bold:true,color:'B9A2FF',charSpacing:2,margin:0});s.addText('Dynamic Deep Data Analysis',{x:1.1,y:1.65,w:10.8,h:1,fontSize:38,bold:true,color:C.white,margin:0,breakLine:false});s.addText(payload.file,{x:1.1,y:2.85,w:10.8,h:.45,fontSize:18,color:'D5D9E2',margin:0});s.addText(payload.subtitle||'Automated Pareto, recurrence, downtime and commonality analysis',{x:1.1,y:3.45,w:10.5,h:.6,fontSize:16,color:'B7C0D0',margin:0});s.addText('Generated from deterministic workbook calculations',{x:1.1,y:5.5,w:8,h:.3,fontSize:10,color:'9099AA',margin:0});footer(s,n++);}
{let s=pptx.addSlide();base(s,'Executive Summary',payload.period||'');let k=payload.kpis||{};addKpi(s,.7,1.35,2.2,'Records',k.rows||'-');addKpi(s,3.05,1.35,2.2,'Machines',k.machines||'-',C.blue);addKpi(s,5.4,1.35,2.2,'Abnormalities',k.events||'-',C.teal);addKpi(s,7.75,1.35,2.2,'Total downtime',k.downtime||'-',C.orange);addKpi(s,10.1,1.35,2.2,'Peak period',k.peak||'-',C.red);s.addText('Key findings',{x:.75,y:2.8,w:3,h:.3,fontSize:17,bold:true,color:C.purple,margin:0});bullets(s,payload.findings||[],.8,3.18,11.7,3.35,15);footer(s,n++);}
function chartSlide(title,img,insights){let s=pptx.addSlide();base(s,title,payload.file);if(img&&fs.existsSync(img))s.addImage({path:img,...imageSizingContain(img,.65,1.25,8.05,5.45)});else{s.addShape(pptx.ShapeType.roundRect,{x:.65,y:1.25,w:8.05,h:5.45,fill:{color:C.light},line:{color:'DED6FA'}});s.addText('Chart generated when applicable',{x:1.6,y:3.4,w:6,h:.35,align:'center',color:C.gray,fontSize:16,margin:0});}s.addShape(pptx.ShapeType.roundRect,{x:9.05,y:1.25,w:3.6,h:5.45,fill:{color:'FAFAFC'},line:{color:'E7E7EE'}});s.addText('Falcon interpretation',{x:9.3,y:1.55,w:3.05,h:.3,fontSize:16,bold:true,color:C.purple,margin:0});bullets(s,insights||[],9.25,1.98,3.1,4.4,12.5);footer(s,n++);return s;}
chartSlide('Occurrence Pareto',payload.charts&&payload.charts.occurrence,payload.occurrenceInsights);
if(payload.charts&&payload.charts.downtime) chartSlide('Downtime Pareto',payload.charts.downtime,payload.downtimeInsights);
if(payload.charts&&payload.charts.time) chartSlide('Time Concentration',payload.charts.time,payload.timeInsights);
if(payload.charts&&payload.charts.heatmap) chartSlide('Machine × Abnormality Commonality',payload.charts.heatmap,payload.commonalityInsights);
{let s=pptx.addSlide();base(s,'Recurrence & Chronic Event Analysis',payload.file);s.addText('Top recurring abnormalities',{x:.75,y:1.35,w:5.6,h:.3,fontSize:17,bold:true,color:C.purple,margin:0});bullets(s,payload.recurrence||[],.8,1.78,5.7,4.9,14);s.addShape(pptx.ShapeType.roundRect,{x:6.85,y:1.35,w:5.7,h:4.95,fill:{color:'FAFAFC'},line:{color:'E7E7EE'}});s.addText('How to use this',{x:7.15,y:1.7,w:4.9,h:.3,fontSize:17,bold:true,color:C.navy,margin:0});bullets(s,['Short median recurrence intervals indicate chronic/repeating conditions.','Combine recurrence with downtime and frequency before assigning priority.','Use machine, process, product/material, and method/operator evidence to confirm root cause.'],7.1,2.15,4.9,3.5,14);footer(s,n++);}
{let s=pptx.addSlide();base(s,'Priority Matrix & Investigation Plan',payload.file);const boxes=[['P1: High frequency + High downtime','Immediate investigation',C.red],['P2: High frequency + Low downtime','Chronic micro-stop reduction',C.orange],['P3: Low frequency + High downtime','Major-loss prevention',C.blue],['P4: Low frequency + Low downtime','Monitor / verify trend',C.teal]];boxes.forEach((b,i)=>{let x=.8+(i%2)*6.1,y=1.45+Math.floor(i/2)*2.05;s.addShape(pptx.ShapeType.roundRect,{x,y,w:5.6,h:1.55,fill:{color:'FAFAFC'},line:{color:b[2],width:2}});s.addText(b[0],{x:x+.25,y:y+.28,w:5.05,h:.35,fontSize:17,bold:true,color:b[2],margin:0});s.addText(b[1],{x:x+.25,y:y+.78,w:5.05,h:.28,fontSize:12,color:C.gray,margin:0});});s.addText('Recommended next checks',{x:.8,y:5.75,w:3.4,h:.3,fontSize:16,bold:true,color:C.purple,margin:0});bullets(s,payload.actions||['Verify top Pareto items at the machine.','Compare process/product/material commonality.','Confirm each suspected cause with evidence before corrective action.'],.85,6.08,11.5,.85,12.5);footer(s,n++);}
for(const sl of pptx._slides){warnIfSlideHasOverlaps(sl,pptx);warnIfSlideElementsOutOfBounds(sl,pptx);}pptx.writeFile({fileName:out});
